### ISSUE TITLE
[DÚVIDA] Saída do desafio

### ISSUE THREAD

**Issue by williamokano** [9Nama/primeira-avaliacao#1]
Fiz esse código que diz o que o enunciado pede
```javascript
console.log([...Array(100)]
.map((v, k) => k + 1)
.map(val => [{num: 5, val:'Nama'}, {num: 7, val:'Team'}].map(itm => (val % itm.num === 0) ? itm.val : '' ).filter(y => y.length > 0).join(' ').trim().length == 0 ? val : [{num: 5, val:'Nama'}, {num: 7, val:'Team'}].map(itm => (val % itm.num === 0) ? itm.val : '' ).filter(y => y.length > 0).join(' ').trim()).join(', '));
```
Entretanto, o enunciado pede que seja **EXATAMENTE** essa saída: `1, 2, 3, 4, Nama, 6, Team, ........ 33, 34, Nama Team, 36 ....., 97, Team, 99, Nama`, logo sinto que errei o desafio, haja visto que minha saída é `1, 2, 3, 4, Nama, 6, Team, 8, 9, Nama, 11, 12, 13, Team, Nama, 16, 17, 18, 19, Nama, Team, 22, 23, 24, Nama, 26, 27, Team, 29, Nama, 31, 32, 33, 34, Nama Team, 36, 37, 38, 39, Nama, 41, Team, 43, 44, Nama, 46, 47, 48, Team, Nama, 51, 52, 53, 54, Nama, Team, 57, 58, 59, Nama, 61, 62, Team, 64, Nama, 66, 67, 68, 69, Nama Team, 71, 72, 73, 74, Nama, 76, Team, 78, 79, Nama, 81, 82, 83, Team, Nama, 86, 87, 88, 89, Nama, Team, 92, 93, 94, Nama, 96, 97, Team, 99, Nama`.

Gostaria de orientações!

**Comment by leonardoobaptistaa** [comment]
@williamokano o enunciado pede que o formato seja exatamente esse, não o resultado em sí.
mas concordo com você que isso causa ambiguidade, vou colocar o resultado todo na descrição.
